/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AnnotatedJiraWorklogDTO { 
    startAt?: number;
    maxResults?: number;
    total?: number;
    worklogs?: Array<any>;
}

