/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnnotatedJiraHistoryDTO } from './annotatedJiraHistoryDTO';


export interface AnnotatedJiraChangelogDTO { 
    startAt?: number;
    maxResults?: number;
    total?: number;
    histories?: Array<AnnotatedJiraHistoryDTO>;
}

