/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AnnotatedJiraLinkedIssueFieldsDTO { 
    summary?: string;
    status?: string;
    priority?: string;
    issuetype?: string;
}

