/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AnnotatedJiraIssueLinkTypeDTO { 
    id?: string;
    self?: string;
    name?: string;
    inward?: string;
    outward?: string;
}

