/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnnotatedJiraIssueLinkTypeDTO } from './annotatedJiraIssueLinkTypeDTO';
import { AnnotatedJiraLinkedIssueDTO } from './annotatedJiraLinkedIssueDTO';


export interface AnnotatedJiraIssueLinkDTO { 
    id?: string;
    self?: string;
    type?: AnnotatedJiraIssueLinkTypeDTO;
    inwardIssue?: AnnotatedJiraLinkedIssueDTO;
    outwardIssue?: AnnotatedJiraLinkedIssueDTO;
}

