/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnnotatedJiraHistoryItemDTO } from './annotatedJiraHistoryItemDTO';


export interface AnnotatedJiraHistoryDTO { 
    id?: string;
    author?: string;
    created?: string;
    items?: Array<AnnotatedJiraHistoryItemDTO>;
}

