/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnnotatedJiraWorklogDTO } from './annotatedJiraWorklogDTO';
import { AnnotatedJiraIssueLinkDTO } from './annotatedJiraIssueLinkDTO';
import { AnnotatedJiraCommentsDTO } from './annotatedJiraCommentsDTO';
import { AnnotatedJiraProgressDTO } from './annotatedJiraProgressDTO';


export interface AnnotatedJiraFieldsDTO { 
    fixVersions?: Array<any>;
    resolution?: string;
    lastViewed?: string;
    priority?: string;
    labels?: Array<string>;
    aggregatetimeoriginalestimate?: number;
    timeestimate?: number;
    versions?: Array<any>;
    issuelinks?: Array<AnnotatedJiraIssueLinkDTO>;
    assignee?: string;
    subtasks?: Array<any>;
    status?: string;
    components?: Array<string>;
    archiveddate?: string;
    aggregatetimeestimate?: number;
    creator?: string;
    reporter?: string;
    aggregateprogress?: AnnotatedJiraProgressDTO;
    progress?: AnnotatedJiraProgressDTO;
    votes?: number;
    hasVoted?: boolean;
    worklog?: AnnotatedJiraWorklogDTO;
    archivedby?: any | null;
    issuetype?: string;
    timespent?: number;
    project?: string;
    aggregatetimespent?: number;
    resolutiondate?: string;
    workratio?: number;
    'watch#'?: number;
    watching?: boolean;
    created?: string;
    updated?: string;
    timeoriginalestimate?: number;
    description?: string;
    summary?: string;
    environment?: string;
    duedate?: string;
    comment?: AnnotatedJiraCommentsDTO;
    timetracking?: { [key: string]: any | null; };
    customFields?: { [key: string]: any | null; };
}

