/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnnotatedJiraChangelogDTO } from './annotatedJiraChangelogDTO';
import { JiraAnnotatedDTO } from './jiraAnnotatedDTO';
import { AnnotatedJiraFieldsDTO } from './annotatedJiraFieldsDTO';


export interface AnnotatedJiraIssueDTO { 
    expand?: string;
    id?: string;
    self?: string;
    key?: string;
    fields?: AnnotatedJiraFieldsDTO;
    changelog?: AnnotatedJiraChangelogDTO;
    annotated?: JiraAnnotatedDTO;
}

