/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GithubPRChange } from './githubPRChange';
import { JiraIssueChange } from './jiraIssueChange';
import { MailingListChange } from './mailingListChange';
import { McpToolCallChange } from './mcpToolCallChange';
import { ClaudeCodePromptBatchStart } from './claudeCodePromptBatchStart';


/**
 * @type GetEventsSince200ResponseInner
 * @export
 */
export type GetEventsSince200ResponseInner = ClaudeCodePromptBatchStart | GithubPRChange | JiraIssueChange | MailingListChange | McpToolCallChange;

