/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GithubPRChange } from './githubPRChange';
import { JiraIssueChange } from './jiraIssueChange';
import { MailingListChange } from './mailingListChange';
import { ClaudeCodePromptStartChange } from './claudeCodePromptStartChange';
import { McpToolCallChange } from './mcpToolCallChange';


/**
 * @type GetEventsSince200ResponseInner
 * @export
 */
export type GetEventsSince200ResponseInner = ClaudeCodePromptStartChange | GithubPRChange | JiraIssueChange | MailingListChange | McpToolCallChange;

