/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GitHubIssueEventDTO { 
    id?: number;
    url?: string;
    actorLogin?: string;
    event?: string;
    commitId?: string;
    commitUrl?: string;
    createdAt?: string;
    labelName?: string;
    labelColor?: string;
    assigneeLogin?: string;
    assignerLogin?: string;
    milestoneTitle?: string;
    renameFrom?: string;
    renameTo?: string;
    reviewRequesterLogin?: string;
    requestedTeamName?: string;
    requestedReviewerLogin?: string;
    dismissedReviewState?: string;
    dismissedReviewDismissalMessage?: string;
    lockReason?: string;
    issueTypeName?: string;
    prevIssueTypeName?: string;
    subIssueNumber?: number;
    parentIssueNumber?: number;
    blockedByNumber?: number;
    blockingNumber?: number;
}

