/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitHubPrDistributionEntryDTO } from './gitHubPrDistributionEntryDTO';


export interface GitHubPrDistributionStatsDTO { 
    dimension?: string;
    entries?: Array<GitHubPrDistributionEntryDTO>;
    entriesPerUser?: Array<GitHubPrDistributionEntryDTO>;
}

