/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitHubCommitFileDTO } from './gitHubCommitFileDTO';


export interface GitHubPullRequestCommitDTO { 
    sha?: string;
    author?: string;
    committer?: string;
    message?: string;
    parentSha0?: string;
    parentShaOthers?: Array<string>;
    additions?: number;
    deletions?: number;
    total?: number;
    files?: Array<GitHubCommitFileDTO>;
    comment_count?: number;
}

