/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitHubPullRequestReviewCommentDTO } from './gitHubPullRequestReviewCommentDTO';
import { GitHubIssueCommentDTO } from './gitHubIssueCommentDTO';
import { GitHubPullRequestExtraFieldsDTO } from './gitHubPullRequestExtraFieldsDTO';


export interface GitHubPullRequestDTO { 
    id?: number;
    number?: number;
    state?: string;
    title?: string;
    body?: string;
    authorLogin?: string;
    createdAt?: string;
    updatedAt?: string;
    closedAt?: string;
    mergedAt?: string;
    draft?: boolean;
    merged?: boolean;
    assigneeLogins?: Array<string>;
    requestedReviewerLogins?: Array<string>;
    labelNames?: Array<string>;
    milestoneTitle?: string;
    headRef?: string;
    headSha?: string;
    baseRef?: string;
    baseSha?: string;
    mergeable?: boolean;
    mergeableState?: string;
    mergedByLogin?: string;
    comments?: number;
    commentsData?: Array<GitHubIssueCommentDTO>;
    reviewComments?: number;
    reviewCommentsData?: Array<GitHubPullRequestReviewCommentDTO>;
    commits?: number;
    additions?: number;
    deletions?: number;
    changedFiles?: number;
    htmlUrl?: string;
    annotated?: GitHubPullRequestExtraFieldsDTO;
}

