/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GitHubIssueCommentDTO { 
    id?: number;
    url?: string;
    body?: string;
    htmlUrl?: string;
    authorLogin?: string;
    createdAt?: string;
    updatedAt?: string;
    authorAssociation?: string;
}

