/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LastCallLimits } from './lastCallLimits';
import { Resources } from './resources';


export interface GitHubRateLimitDTO { 
    resources?: Resources;
    lastCallLimits?: LastCallLimits;
}

