/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GitHubPullRequestReviewCommentDTO { 
    id?: number;
    pullRequestReviewId?: number;
    diffHunk?: string;
    path?: string;
    position?: number;
    originalPosition?: number;
    commitId?: string;
    originalCommitId?: string;
    inReplyToId?: number;
    authorLogin?: string;
    body?: string;
    createdAt?: string;
    updatedAt?: string;
    htmlUrl?: string;
    authorAssociation?: string;
    line?: number;
    originalLine?: number;
    side?: string;
    startLine?: number;
    originalStartLine?: number;
    startSide?: string;
    subjectType?: string;
}

