/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IssueProgressDTO } from './issueProgressDTO';
import { IssueLinkDTO } from './issueLinkDTO';
import { IssueCommentDTO } from './issueCommentDTO';


export interface IssueFieldsDTO { 
    fixVersions?: Array<any>;
    resolution?: string;
    lastViewed?: string;
    priority?: string;
    labels?: Array<string>;
    aggregatetimeoriginalestimate?: number;
    timeestimate?: number;
    versions?: Array<string>;
    issuelinks?: Array<IssueLinkDTO>;
    assignee?: string;
    subtasks?: Array<any>;
    status?: string;
    components?: Array<string>;
    archiveddate?: string;
    aggregatetimeestimate?: number;
    creator?: string;
    reporter?: string;
    aggregateprogress?: IssueProgressDTO;
    progress?: IssueProgressDTO;
    votes?: number;
    hasVoted?: boolean;
    worklogs?: Array<any>;
    archivedby?: any | null;
    issuetype?: string;
    timespent?: number;
    project?: string;
    aggregatetimespent?: number;
    resolutiondate?: string;
    workratio?: number;
    watchCount?: number;
    watching?: boolean;
    created?: string;
    updated?: string;
    timeoriginalestimate?: number;
    description?: string;
    summary?: string;
    environment?: string;
    duedate?: string;
    comments?: Array<IssueCommentDTO>;
    timetracking?: { [key: string]: any | null; };
    customFields?: { [key: string]: any | null; };
}

