/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IssueCommentDTO { 
    id?: string;
    author?: string;
    body?: string;
    updateAuthor?: string;
    created?: string;
    updated?: string;
}

