/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IssuesCriteriaDTO { 
    fromYear?: number;
    toYear?: number;
    usernamePattern?: string;
    fromNumber?: number;
    toNumber?: number;
    keyPattern?: string;
    summaryContains?: string;
    descriptionContains?: string;
    authorContains?: string;
    commentsContains?: string;
    commentAuthorContains?: string;
    excludedTypes?: string;
    excludedResolutions?: string;
    excludedStatuses?: string;
    excludedPriorities?: string;
    labelsContains?: string;
    pullRequestAvailableLabel?: string;
    componentsContains?: string;
    analysisSummaryContains?: string;
    analysisUserExtraPromptsContains?: string;
    analysisSummaryUpdatedFrom?: string;
    analysisSummaryUpdatedTo?: string;
    analysisSummaryMinTokensK?: number;
    analysisSummaryMaxTokensK?: number;
    analysisAvailability?: string;
    developmentWorkDescribedContains?: string;
    developmentWorkUserExtraPromptsContains?: string;
    developmentWorkUpdatedFrom?: string;
    developmentWorkUpdatedTo?: string;
    developmentWorkMinTokensK?: number;
    developmentWorkMaxTokensK?: number;
    developmentWorkAvailability?: string;
    personalInterrestCommentContains?: string;
    personalInterrestMinPriority?: number;
    personalInterrestMaxPriority?: number;
    personalInterrestAvailability?: string;
}

