/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IssuesCriteriaDTO } from './issuesCriteriaDTO';


export interface IssuesCompareQueryDTO { 
    leftCriteria?: IssuesCriteriaDTO;
    leftLimit?: number;
    rightCriteria?: IssuesCriteriaDTO;
    rightLimit?: number;
    fillCommonIds?: boolean;
}

