/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IssueLinkTypeDTO } from './issueLinkTypeDTO';
import { LinkedIssueDTO } from './linkedIssueDTO';


export interface IssueLinkDTO { 
    id?: string;
    type?: IssueLinkTypeDTO;
    inwardIssue?: LinkedIssueDTO;
    outwardIssue?: LinkedIssueDTO;
}

