/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IssueHistoryItemDTO } from './issueHistoryItemDTO';


export interface IssueHistoryDTO { 
    id?: string;
    author?: string;
    created?: string;
    items?: Array<IssueHistoryItemDTO>;
}

