/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IssueExtraFieldsDTO { 
    analysisSummary?: string;
    analysisSummaryLastUpdateTime?: string;
    analysisSummaryTokensConsumed?: number;
    analysisUserExtraPrompts?: Array<string>;
    developmentWorkDescribed?: string;
    developmentWorkLastUpdateTime?: string;
    developmentWorkTokensConsumed?: number;
    developmentWorkUserExtraPrompts?: Array<string>;
    personalInterrestComment?: string;
    personalInterrestPriority10?: number;
}

