/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IssuesCompareIdsResultDTO { 
    leftOnlyIds?: Array<string>;
    commonIds?: Array<string>;
    commonCount?: number;
    rightOnlyIds?: Array<string>;
}

