/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JiraUserActivityMonthStatsDTO { 
    month?: string;
    jiraIssueCreatedCount?: number;
    jiraIssueUpdatedCount?: number;
    jiraIssueCommentedCount?: number;
    jiraIssueClosedRejectedCount?: number;
    jiraIssueCloseResolvedCount?: number;
}

