/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnnotatedJiraLinkedIssueFieldsDTO } from './annotatedJiraLinkedIssueFieldsDTO';


export interface LinkedIssueDTO { 
    id?: string;
    key?: string;
    fields?: AnnotatedJiraLinkedIssueFieldsDTO;
}

