/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SenderCountDTO } from './senderCountDTO';
import { MonthCountDTO } from './monthCountDTO';


export interface MailMessagePartitionStatsDTO { 
    statsPerMonth?: Array<MonthCountDTO>;
    statsPerSender?: Array<SenderCountDTO>;
}

