/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MailMessageExtraFieldsDTO } from './mailMessageExtraFieldsDTO';


export interface MailMessageAnnotationDTO { 
    messageId?: string;
    annotated?: MailMessageExtraFieldsDTO;
}

