/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MailMessageExtraFieldsDTO } from './mailMessageExtraFieldsDTO';


export interface MailMessageDTO { 
    messageId?: string;
    inReplyTo?: string;
    references?: Array<string>;
    subject?: string;
    from?: string;
    to?: Array<string>;
    cc?: Array<string>;
    date?: string;
    bodyText?: string;
    annotated?: MailMessageExtraFieldsDTO;
}

