/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MailMessageCriteriaDTO { 
    fromMonth?: string;
    toMonth?: string;
    fromPattern?: string;
    subjectPattern?: string;
    bodyPattern?: string;
    subjectContains?: string;
    bodyContains?: string;
    fromContains?: string;
    toCcContains?: string;
    analysisSummaryContains?: string;
    analysisUserExtraPromptsContains?: string;
    analysisSummaryUpdatedFrom?: string;
    analysisSummaryUpdatedTo?: string;
    analysisSummaryMinTokensK?: number;
    analysisSummaryMaxTokensK?: number;
    analysisAvailability?: string;
    developmentWorkDescribedContains?: string;
    developmentWorkUserExtraPromptsContains?: string;
    developmentWorkUpdatedFrom?: string;
    developmentWorkUpdatedTo?: string;
    developmentWorkMinTokensK?: number;
    developmentWorkMaxTokensK?: number;
    developmentWorkAvailability?: string;
    personalInterrestCommentContains?: string;
    personalInterrestMinPriority?: number;
    personalInterrestMaxPriority?: number;
    personalInterrestAvailability?: string;
}

