/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NearbyJiraIssuesDTO { 
    prevStillOpen?: string;
    prevStillOpenCreatedBySameAuthor?: string;
    prevCreatedBySameAuthor?: string;
    nextStillOpen?: string;
    nextStillOpenCreatedBySameAuthor?: string;
    nextCreatedBySameAuthor?: string;
}

