/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NearbyGitHubPullRequestsDTO { 
    prevStillOpen?: number;
    prevStillOpenCreatedBySameAuthor?: number;
    prevCreatedBySameAuthor?: number;
    nextStillOpen?: number;
    nextStillOpenCreatedBySameAuthor?: number;
    nextCreatedBySameAuthor?: number;
}

