/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RateLimit } from './rateLimit';


export interface Resources { 
    core?: RateLimit;
    graphql?: RateLimit;
    search?: RateLimit;
    code_search?: RateLimit;
    source_import?: RateLimit;
    integration_manifest?: RateLimit;
    actions_runner_registration?: RateLimit;
    scim?: RateLimit;
    dependency_snapshots?: RateLimit;
    dependency_sbom?: RateLimit;
    code_scanning_autofix?: RateLimit;
    copilot_usage_records?: RateLimit;
}

