/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SourceGitHubGitUserDTO } from './sourceGitHubGitUserDTO';


export interface SourceGitHubCommitDetailDTO { 
    author?: SourceGitHubGitUserDTO;
    committer?: SourceGitHubGitUserDTO;
    message?: string;
    comment_count?: number;
}

