/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SourceGitHubCommitStatsDTO } from './sourceGitHubCommitStatsDTO';
import { SourceGitHubCommitDetailDTO } from './sourceGitHubCommitDetailDTO';
import { SourceGitHubCommitFileDTO } from './sourceGitHubCommitFileDTO';
import { SourceGitHubCommitParentDTO } from './sourceGitHubCommitParentDTO';
import { SourceGitHubUserDTO } from './sourceGitHubUserDTO';


export interface SourceGitHubCommitDTO { 
    sha?: string;
    commit?: SourceGitHubCommitDetailDTO;
    author?: SourceGitHubUserDTO;
    committer?: SourceGitHubUserDTO;
    parents?: Array<SourceGitHubCommitParentDTO>;
    stats?: SourceGitHubCommitStatsDTO;
    files?: Array<SourceGitHubCommitFileDTO>;
    html_url?: string;
}

