/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserMailMessagePerMonthStatsDTO { 
    month?: string;
    messageCount?: number;
    threadStartedCount?: number;
    replyCount?: number;
    firstMessages?: Array<string>;
}

