/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPullRequestCreatePerYearStatsDTO } from './userPullRequestCreatePerYearStatsDTO';


export interface UserGitHubPullRequestStatsDTO { 
    user?: string;
    pullRequestCreateCount?: number;
    mergedCount?: number;
    closedNotMergedCount?: number;
    openCount?: number;
    draftCount?: number;
    commentsCount?: number;
    reviewCommentsCount?: number;
    commitsCount?: number;
    additionsCount?: number;
    deletionsCount?: number;
    changedFilesCount?: number;
    perYear?: { [key: string]: UserPullRequestCreatePerYearStatsDTO; };
}

