/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserActivityMonthStatsDTO { 
    month?: string;
    jiraIssueCreatedCount?: number;
    jiraIssueUpdatedCount?: number;
    jiraIssueCommentedCount?: number;
    jiraIssueClosedRejectedCount?: number;
    jiraIssueCloseResolvedCount?: number;
    githubPullRequestCreatedCount?: number;
    githubPullRequestUpdatedCount?: number;
    githubPullRequestCommentedCount?: number;
    githubPullRequestMergedCount?: number;
    githubPullRequestClosedCount?: number;
    mailMessageSentCount?: number;
    mailMessageRepliedCount?: number;
    mailMessageVotedCount?: number;
}

