/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserMailMessagePerMonthStatsDTO } from './userMailMessagePerMonthStatsDTO';


export interface UserMailMessageStatsDTO { 
    user?: string;
    messageCount?: number;
    threadStartedCount?: number;
    replyCount?: number;
    perMonth?: { [key: string]: UserMailMessagePerMonthStatsDTO; };
}

