/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserPullRequestCreatePerYearStatsDTO { 
    year?: number;
    pullRequestCreateCount?: number;
    mergedCount?: number;
    closedNotMergedCount?: number;
    openCount?: number;
    draftCount?: number;
    commentsCount?: number;
    reviewCommentsCount?: number;
    commitsCount?: number;
    additionsCount?: number;
    deletionsCount?: number;
    changedFilesCount?: number;
    firstPullRequests?: Array<number>;
}

