/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserActivityMonthStatsDTO } from './userActivityMonthStatsDTO';


export interface UserActivityStatsDTO { 
    user?: string;
    jiraIssueCreatedCount?: number;
    jiraIssueUpdatedCount?: number;
    jiraIssueCommentedCount?: number;
    jiraIssueClosedRejectedCount?: number;
    jiraIssueCloseResolvedCount?: number;
    githubPullRequestCreatedCount?: number;
    githubPullRequestUpdatedCount?: number;
    githubPullRequestCommentedCount?: number;
    githubPullRequestMergedCount?: number;
    githubPullRequestClosedCount?: number;
    mailMessageSentCount?: number;
    mailMessageRepliedCount?: number;
    mailMessageVotedCount?: number;
    perMonth?: { [key: string]: UserActivityMonthStatsDTO; };
}

