/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JiraUserActivityStatsDTO } from './jiraUserActivityStatsDTO';
import { MailMessageUserActivityStatsDTO } from './mailMessageUserActivityStatsDTO';
import { GithubUserActivityStatsDTO } from './githubUserActivityStatsDTO';


export interface UserActivityStatsResultDTO { 
    jira?: { [key: string]: JiraUserActivityStatsDTO; };
    github?: { [key: string]: GithubUserActivityStatsDTO; };
    mail?: { [key: string]: MailMessageUserActivityStatsDTO; };
}

