/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserIssueCreatePerYearStatsDTO } from './userIssueCreatePerYearStatsDTO';


export interface UserJiraIssueStatsDTO { 
    user?: string;
    issueCreateCount?: number;
    closedIssuesCount?: number;
    closedBySelfIssuesCount?: number;
    closedForOtherIssuesCount?: number;
    openIssuesCount?: number;
    rejectedIssuesCount?: number;
    reopenedIssuesCount?: number;
    issuesCommentsCount?: number;
    perYear?: { [key: string]: UserIssueCreatePerYearStatsDTO; };
}

